# Generated by Django 5.0.5 on 2024-08-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ozon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул')),
                ('barcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Штрих-код')),
                ('price', models.IntegerField(default=10000, verbose_name='Цена руб.')),
                ('length', models.IntegerField(default=180, verbose_name='Длина упаковки мм.')),
                ('width', models.IntegerField(default=120, verbose_name='Ширина упаковки мм.')),
                ('height', models.IntegerField(default=100, verbose_name='Высота упаковки мм.')),
                ('weight', models.IntegerField(default=200, verbose_name='вес')),
                ('annotacion', models.TextField(default='Совместимость с брендом: \nМатериал: \nЦвет: ', max_length=5000, verbose_name='Аннотация')),
                ('model_list', models.TextField(max_length=5000, verbose_name='Список совместимых устройств')),
                ('xcel_shablon', models.FileField(upload_to='ozon_shablons', verbose_name='XL шаблон')),
                ('image', models.FileField(blank=True, null=True, upload_to='foto', verbose_name='Фото')),
            ],
        ),
    ]
