# Generated by Django 5.0.5 on 2024-05-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozon',
            name='xcel_shablon',
            field=models.FileField(default=1, upload_to='ozon_shablons', verbose_name='XL шаблон'),
            preserve_default=False,
        ),
    ]
