# Generated by Django 5.0.5 on 2024-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0003_alter_ozon_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozon',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Штрих-код'),
        ),
    ]
