# Generated by Django 5.0.5 on 2024-05-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0005_ozon_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozon',
            name='article',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул'),
        ),
    ]
