# Generated by Django 5.0.5 on 2024-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0006_alter_ozon_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozon',
            name='annotacion',
            field=models.TextField(default='Совместимость с брендом: \nМатериал: \nЦвет: ', max_length=5000, verbose_name='Аннотация'),
        ),
    ]
