# Generated by Django 5.0.5 on 2024-07-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0007_alter_ozon_annotacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozon',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='foto', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ozon',
            name='annotacion',
            field=models.TextField(default='Совместимость с брендом:\nМатериал: \nЦвет: ', max_length=5000, verbose_name='Аннотация'),
        ),
    ]
