# Generated by Django 5.0.5 on 2024-07-31 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='purchaseorder', verbose_name='Фото')),
                ('name', models.CharField(max_length=250, verbose_name='Название товара')),
                ('code', models.CharField(max_length=100, verbose_name='Код товара')),
                ('barcodes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Баркоды')),
                ('quantity', models.IntegerField(verbose_name='Заказано шт')),
                ('summ', models.FloatField(verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purchaseorder.order')),
            ],
        ),
    ]
