# Generated by Django 5.0.5 on 2024-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='fact',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фактическое количество'),
        ),
    ]
