# Generated by Django 5.0.5 on 2024-08-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0002_purchaseorder_comment_purchaseorder_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=0, max_length=100, verbose_name='Слагифицирован'),
            preserve_default=False,
        ),
    ]
