# Generated by Django 5.0.5 on 2024-08-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0002_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Api ID заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.SlugField(max_length=100, unique=True, verbose_name='ID товара'),
        ),
    ]
