# Generated by Django 5.0.5 on 2024-08-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0003_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Посчитано'),
        ),
    ]
