# Generated by Django 5.0.5 on 2024-08-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0003_alter_order_order_id_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='xl_doc',
            field=models.FileField(blank=True, null=True, upload_to='purchaseorder', verbose_name='Итоговый документ'),
        ),
    ]
