# Generated by Django 5.0.5 on 2024-08-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0004_purchaseorder_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='plus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Посчитано'),
        ),
    ]
