# Generated by Django 5.0.5 on 2024-08-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0005_alter_purchaseorder_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='fact',
            field=models.IntegerField(default=0, verbose_name='Фактическое количество'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Посчитано'),
        ),
    ]
