# Generated by Django 5.0.5 on 2024-07-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanner',
            options={'default_related_name': 'barcods', 'ordering': ('-scan_date',), 'verbose_name': 'штрих-код', 'verbose_name_plural': 'Штрих-коды'},
        ),
    ]
